In [10]:
#Pivot tables
import pandas as pd
birth = pd.read_csv(r'D:\GitHub\Data-Science\Pandas\Exercise1\US_births_1994-2003_CDC_NCHS.csv')
birth.head(2)

   year  month  date_of_month  day_of_week  births
0  1994      1              1            6    8096
1  1994      1              2            7    7772

In [11]:
month_births = birth.pivot_table(index='month',values='births',aggfunc=sum)
month_births

month
1     3232517
2     3018140
3     3322069
4     3185314
5     3350907
6     3296530
7     3498783
8     3525858
9     3439698
10    3378814
11    3171647
12    3301860
Name: births, dtype: int64

In [12]:
avg_births_mnth = birth.pivot_table(index='month',values='births')
avg_births_mnth

month
1     10427.474194
2     10702.624113
3     10716.351613
4     10617.713333
5     10809.377419
6     10988.433333
7     11286.396774
8     11373.735484
9     11465.660000
10    10899.400000
11    10572.156667
12    10651.161290
Name: births, dtype: float64

In [13]:
#Find the sum total of births monthwise, datewise, daywise
birth.pivot_table(index = ["month", "date_of_month"], columns = "day_of_week", values = "births", aggfunc=sum)

day_of_week                1        2        3        4        5        6  \
month date_of_month
1     1              15120.0   7790.0  16132.0   8213.0   8163.0  16939.0
      2               7883.0  19754.0  10420.0  20777.0   9784.0   7637.0
      3              21265.0   9999.0  23067.0  12134.0  23161.0   8437.0
      4              10396.0  23951.0  11315.0  23737.0  12433.0  16991.0
      5              10556.0  12004.0  23293.0  11243.0  24058.0   8760.0
      6              21676.0  11843.0  11718.0  23666.0  11506.0  17699.0
      7              11371.0  24013.0  11428.0  11901.0  23531.0   8681.0
      8              21283.0  12248.0  22744.0  11526.0  11772.0  17403.0
      9              10434.0  23123.0  11391.0  22809.0  11469.0   8466.0
      10             21916.0  11665.0  23304.0  12318.0  23848.0   8612.0
      11             10816.0  24029.0  11279.0  23459.0  12048.0  16702.0
      12             10553.0  12190.0  23624.0  11416.0  23738.0   8399.0
      13             21284.0  11850.0  11626.0  22768.0  11071.0  17135.0
      14             11344.0  24153.0  11542.0  11767.0  23494.0   8887.0
      15             20632.0  12101.0  23189.0  11491.0  11704.0  17025.0
      16             10417.0  23222.0  11697.0  23208.0  11535.0   8444.0
      17             21168.0  11345.0  23194.0  12077.0  23176.0   8698.0
      18             10508.0  23627.0  11252.0  23941.0  12015.0  16640.0
      19             10325.0  11812.0  23340.0  11331.0  23336.0   8301.0
      20             21286.0  11806.0  11901.0  23870.0  11481.0  17094.0
      21             10741.0  23588.0  11650.0  12027.0  23478.0   8746.0
      22             21812.0  12104.0  23343.0  11680.0  11677.0  17466.0
      23             10640.0  23627.0  11970.0  23403.0  11389.0   8587.0
      24             22309.0  11344.0  23382.0  12235.0  23300.0   8525.0
      25             10973.0  24234.0  11096.0  23721.0  11867.0  16875.0
      26             10771.0  11915.0  23393.0  11380.0  23188.0   8400.0
      27             21758.0  11813.0  11548.0  23838.0  11340.0  17127.0
      28             11139.0  24024.0  11483.0  11745.0  23339.0   8781.0
      29             21643.0  11963.0  22935.0  11513.0  11571.0  17623.0
      30             10515.0  23596.0  11902.0  23233.0  11616.0   8473.0
...                      ...      ...      ...      ...      ...      ...
12    2              22532.0  25631.0  12003.0  11976.0  11379.0  17051.0
      3              11275.0  25103.0  24881.0  11990.0  11591.0   8585.0
      4              21522.0  12293.0  24233.0  24182.0  11661.0   8333.0
      5              10772.0  24283.0  12307.0  23930.0  23286.0   8368.0
      6              10956.0  11923.0  23551.0  11892.0  23107.0  16448.0
      7              10872.0  12329.0  11335.0  23740.0  11424.0  16867.0
      8              22192.0  12354.0  11849.0  11337.0  23429.0   8189.0
      9              21955.0  24524.0  11824.0  11728.0  11205.0  16836.0
      10             11345.0  24444.0  24025.0  11685.0  11459.0   8461.0
      11             21935.0  12407.0  23832.0  23673.0  11284.0   8442.0
      12             11106.0  24973.0  12510.0  24378.0  23617.0   8418.0
      13             10830.0  11884.0  23405.0  11948.0  22001.0  16328.0
      14             11063.0  12667.0  11716.0  23716.0  12143.0  16892.0
      15             23118.0  12430.0  12623.0  11962.0  23826.0   8447.0
      16             23254.0  25856.0  12256.0  12441.0  12144.0  17490.0
      17             12049.0  25481.0  25305.0  12572.0  12453.0   8726.0
      18             23415.0  13300.0  25368.0  26137.0  12634.0   8979.0
      19             11502.0  25931.0  13072.0  25523.0  25977.0   8804.0
      20             12497.0  12880.0  25434.0  13558.0  26242.0  17792.0
      21             12414.0  13508.0  12391.0  25090.0  13185.0  17618.0
      22             24988.0  13286.0  12166.0  11504.0  23141.0   8879.0
      23             21739.0  24659.0  11149.0  10591.0  10087.0  16352.0
      24              7448.0  18043.0  18225.0   8464.0   8046.0   7898.0
      25             13593.0   6443.0  13721.0  13683.0   7020.0   6674.0
      26              8454.0  19517.0  10735.0  21224.0  20293.0   7735.0
      27             11579.0  11131.0  24755.0  13762.0  25592.0  17325.0
      28             11980.0  13158.0  12398.0  26062.0  13918.0  18056.0
      29             25029.0  13637.0  12629.0  12189.0  25441.0   9365.0
      30             24817.0  27959.0  13297.0  11935.0  12051.0  18270.0
      31             10018.0  24263.0  24192.0  11389.0   9335.0   8809.0

day_of_week                7
month date_of_month
1     1               7828.0
      2              15588.0
      3               7416.0
      4               7807.0
      5              15022.0
      6               7505.0
      7              15482.0
      8               7821.0
      9              15646.0
      10              7704.0
      11              7642.0
      12             14738.0
      13              7355.0
      14             15359.0
      15              7988.0
      16             15622.0
      17              7679.0
      18              7690.0
      19             14893.0
      20              7338.0
      21             15369.0
      22              7956.0
      23             16022.0
      24              7597.0
      25              7586.0
      26             14821.0
      27              7387.0
      28             15174.0
      29              8009.0
      30             15699.0
...                      ...
12    2               7216.0
      3              15451.0
      4               7980.0
      5               7503.0
      6               7614.0
      7              14849.0
      8              14920.0
      9               7333.0
      10             15402.0
      11              7936.0
      12              7528.0
      13              7460.0
      14             14841.0
      15             15081.0
      16              7309.0
      17             15604.0
      18              8130.0
      19              7732.0
      20              7792.0
      21             15222.0
      22             15209.0
      23              7082.0
      24             13800.0
      25              7192.0
      26              7432.0
      27              7829.0
      28             15509.0
      29             16085.0
      30              7679.0
      31             15317.0

[366 rows x 7 columns]

In [14]:
birth.pivot_table(index = ["month", "date_of_month", "day_of_week"], values = "births", aggfunc=sum)

month  date_of_month  day_of_week
1      1              1              15120
                      2               7790
                      3              16132
                      4               8213
                      5               8163
                      6              16939
                      7               7828
       2              1               7883
                      2              19754
                      3              10420
                      4              20777
                      5               9784
                      6               7637
                      7              15588
       3              1              21265
                      2               9999
                      3              23067
                      4              12134
                      5              23161
                      6               8437
                      7               7416
       4              1              10396
                      2              23951
                      3              11315
                      4              23737
                      5              12433
                      6              16991
                      7               7807
       5              1              10556
                      2              12004
                                     ...
12     27             6              17325
                      7               7829
       28             1              11980
                      2              13158
                      3              12398
                      4              26062
                      5              13918
                      6              18056
                      7              15509
       29             1              25029
                      2              13637
                      3              12629
                      4              12189
                      5              25441
                      6               9365
                      7              16085
       30             1              24817
                      2              27959
                      3              13297
                      4              11935
                      5              12051
                      6              18270
                      7               7679
       31             1              10018
                      2              24263
                      3              24192
                      4              11389
                      5               9335
                      6               8809
                      7              15317
Name: births, dtype: int64